### ISSUE TITLE
Not found `npm` with nvm!

### ISSUE THREAD

**Issue by sergeysova** [noseglid/atom-build-npm-apm#16]
I install node by nvm.
![image](https://cloud.githubusercontent.com/assets/5620073/14686864/5be7bd68-0743-11e6-845a-a8273218c293.png)

**Comment by noseglid** [comment]
So where is npm (what folder) ?

Build doesn't care much about how binaries enter your environment as long as the path is listen in the list you get there.

**Comment by sergeysova** [comment]
@noseglid 
![image](https://cloud.githubusercontent.com/assets/5620073/14687270/4e245c48-0745-11e6-9786-e5481d375dce.png)

**Comment by sergeysova** [comment]
@noseglid I use [project-manager](https://atom.io/packages/project-manager)
And that project was loaded after Atom starts
If I open Atom with command `atom ~/projects/project16` build works
If I open Atom with .desktop file and project was loaded automatically and if I switch projects

**Comment by noseglid** [comment]
So, having never used `nvm` myself I'm guessing it modified the `PATH` variable when you switch node version.

It works when you open it from the terminal because the `PATH` is set in that case.

It does not work when you "double click an icon", because the environment there does not have the `PATH` set properly to your (versioned) `npm`.

**Comment by sergeysova** [comment]
@noseglid Do you have any solutions?

**Comment by noseglid** [comment]
Oh I though it was obvious. You need to make sure that the folder with `npm` is in your `PATH` in all environments.
